### ISSUE TITLE
ModuleNotFoundError: No module named 'tfrecord.torch'

### ISSUE THREAD

**Issue by praateekmahajan** [vahidk/tfrecord#1]
As title suggests.

Probably there is a requirement to edit

`tfrecord/__init__.py` to also include `from .torch import *`

and inside

`tfrecord/torch/__init__.py` say `from .dataset import TFRecordDataset, MultiTFRecordDataset`

**Comment by vahidk** [comment]
Thanks. I believe this is resolved now if you update to 1.1.
