### ISSUE TITLE
Creating index file from multiple tfrecord files?

### ISSUE THREAD

**Issue by sshleifer** [vahidk/tfrecord#14]
How might one go about creating an index file before using `MultiTFRecordDataset`?

In my case, dataset is 20 files in dir `data/proc_data/IMDB/unsup/bt-0.9/0/`.

Thanks!

**Comment by vahidk** [comment]
Please see the readme.md.

**Comment by sshleifer** [comment]
Have read the README, but don't see a relevant command. For example, `python3 -m tfrecord.tools.tfrecord2idx <tfrecord path> <index path>` can't take a pattern as the first argument.

**Comment by vahidk** [comment]
That is intentionally left a mystery for the users to resolve as an exercise.

**Comment by ram-ch** [comment]
#!/bin/bash

`for f in $(ls train_tfrecords/*.tfrec)
do
   echo $f
   python -m tfrecord.tools.tfrecord2idx $f train_tfrecord.index
done`


Created this shell script, but it dosent create any index file
