### ISSUE TITLE
infinity loop when reading multi tfrecords

### ISSUE THREAD

**Issue by charles-loomai** [vahidk/tfrecord#32]
Hi, thanks for your awesome tfrecord

```python
loader = tfrecord.multi_tfrecord_loader(
        tfrecord_pattern, index_pattern, splits, description
    )
    qbar = tqdm(enumerate(loader))
    for i, record in qbar:
         # do something
         # infinity loop, [never ends]
    # do something else [never enter this part]
```
I came across a problem when loading multiple tfrecords with `tfrecord.multi_tfrecord_loader`.
The loop seems never end...

**Comment by vahidk** [comment]
This is intended behavior. Use tfrecord_loader instead if you just want to read the data once.

**Comment by charles-loomai** [comment]
sorry for bothering you again. Then I guess `MultiTFRecordDataset` is also an infinity iterator.

any ideas or suggestions if I want to add an alternative function that reads multiple tfrecords only once?

**Comment by charles-loomai** [comment]
@vahidk 
a newbie question: will it be efficient to read from over 200GB tfrecord - if I store the database in a single file?

**Comment by vahidk** [comment]
TFRecordDataset uses tfrecord_loader and reads a dataset only once.

**Comment by charles-loomai** [comment]
@vahidk 
I'm sorry, maybe I didn't make it very clear.
I have over 1.1 million small wave files, I want to train a speaker recognition network. But if I directly read files the training is very slow, the GPU-Util is only 20% or less. 
What I'm looking for is to convert the wave files into some database to speed up the loading process. Ideally, I want a dataloader that can support multiple workers to read data.. 
Here is what I found:
- converting all files into one tfrecord (~300GB), loading `tfrecord.tfrecord_loader` is a little faster than directly reading from wave files, but still slow. ~GPU-Util can be up to 40%
- converting all files into 500 tfrecord files (~600MB each), loading with `multi_tfrecord_loader`, but It does not support multiple workers... the GPU-util cannot still go up.

now I don't know what to do next, any suggestions?
