### ISSUE TITLE
When i create the index file of tfrecord file, it occur Failed to parse TFRecord

### ISSUE THREAD

**Issue by Lizhen0797** [vahidk/tfrecord#42]
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py:125: RuntimeWarning: 'tfrecord.tools.tfrecord2idx' found in sys.modules after import of package 'tfrecord.tools', but prior to execution of 'tfrecord.tools.tfrecord2idx'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Failed to parse TFRecord.

the TFRecord's compression_type is GZIP

**Comment by vahidk** [comment]
Currently compressed tfrecords are not supported. PRs are welcome.
