### ISSUE TITLE
Scaling to numerous TFRecordDataset with shuffling  

### ISSUE THREAD

**Issue by mboudiaf** [vahidk/tfrecord#50]
Hi,

First of all, thanks a lot for this great library.

**Context**:  Based on your library, I am trying to implement a pytorch version of recent Few-Shot Image classification benchmark https://github.com/google-research/meta-dataset. The idea is quite simple: each category of a dataset has its own .tfrecords. https://github.com/google-research/meta-dataset/blob/d6574b42c0f501225f682d651c631aef24ad0916/meta_dataset/data/reader.py#L283. Therefore, a TFRecordDataset is created for each class of the dataset, and each is shuffled with 1000 samples. Importantly, in this setting, some datasets have over 1000 classes, but somehow their pipeline scales pretty well in terms of memory.

**Problem**: If I want to reproduce this with the current library, each TFecordDataset will load 1000 (processed) samples in memory for each of the 1000 classes to be able to shuffle them, which becomes rapidly intractable. In an attempt to solve this, I tried to postpone the decoding later in the pipeline, such that all what is stored in memory by each dataset are raw records, which hopefully require less memory. Specifically, my idea was to replace https://github.com/vahidk/tfrecord/blob/d7217998fb884a6d6769c9f22009795f403a5ed9/tfrecord/reader.py#L205 by:
```python3 
yield record
```
and perform the parsing operations only for the current batch of data. Unfortunately, I am facing the issue that the parsing of a record seems to only work properly if the record parsed was the last yielded by the iterator. Specifically, consider the following simple modif of TFRecordDataset:
```python3 
        it = reader.tfrecord_loader(data_path=self.data_path,
                                    index_path=self.index_path,
                                    description=self.description,
                                    shard=shard,
                                    sequence_description=self.sequence_description)
        while True:
            it1 = next(it)
            it2 = next(it)
            yield it2
```
Then downstream parsing of the yielded raw record will work just fine. However, a simple modification :
```python3 
        while True:
            it1 = next(it)
            it2 = next(it)
            yield it1
```
will result in `google.protobuf.message.DecodeError: Error parsing message` down the line. 

My questions are:
1) Do you think my overall approach is suited to make the problem scalable ?
2) Do you have any idea why I'm facing the problem I just described ?

Thanks a lot !

**Comment by vahidk** [comment]
You can use MultiTFRecordDataset for this.
