### ISSUE TITLE
Issue with shuffle=True, when using with pytorch dataloader

### ISSUE THREAD

**Issue by anjith2006** [vahidk/tfrecord#51]
Hi,

Thank you for the very useful repo. 

ValueError: DataLoader with IterableDataset: expected unspecified shuffle option, but got shuffle=True

is there a way to use shuffling with  the interface. Also is there a way to preceompute 
the length of the dataset.

Thanks

**Comment by vahidk** [comment]
TFRecordDataset and MultiTFRecordDataset both shuffle the data internally. Provide a "shuffle_queue_size" to the dataset.

**Comment by vahidk** [comment]
I added an example in the Readme.md
