### ISSUE TITLE
Iterating over multiple tf record files once but randomly

### ISSUE THREAD

**Issue by Spandan-Madan** [vahidk/tfrecord#52]
I'm trying to train ImageNet from scratch and tfrecords are much faster for that. The dataset exists in multiple tf record files. With one single tf record it is straightforward, I just use TFRecordDataset. However, I am unsure how to use the MultiTFRecordDataset for this purpose. For some reason, the data loader hangs and goes into an infinite loop. 

Is this the intended purpose of MultiTFRecordDataset? 

Thanks in advance!

**Comment by vahidk** [comment]
Yes MultiTFRecordDataset should work. I don't have the bandwidth to debug codes, you need to put some checkpoints and debug your code.

**Comment by Spandan-Madan** [comment]
Thanks for the response! I've been investigating and it seems that it goes into an infinite loop as number of tf records is increased. Works fine for 2-3 tf records, but not beyond that. Any suggestions for where I should start looking/what might be up? Any leads would be helpful :)

Thanks in advance!

**Comment by vahidk** [comment]
I have used MultiTFRecordDataset with ~100 files with no problem. If you are using shuffling, shuffle_queue_size should be small for large # of files as MultiTFRecordDataset keeps NumFiles x shuffle_queue_size records in memory. Also you probably need to create a tfindex file for all of your tfrecord files.

**Comment by Spandan-Madan** [comment]
Really appreciate you taking the time to share the details. I'll try these out!

**Comment by Spandan-Madan** [comment]
Isolated the issue, it's in iterator_utils.sample_iterators(). Created a new issue with all the details, would love your input, thanks!
