### ISSUE TITLE
Google Cloud Bucket support

### ISSUE THREAD

**Issue by zhengzangw** [vahidk/tfrecord#58]
Pytorch xla has `torch_xla.utils.tf_record_reader.TfRecordReader` which supports loading from GCB. When I use the GCB location for `TFRecordDataset` , I got

```log
FileNotFoundError: [Errno 2] No such file or directory: 'gs://xxx'
```

I wonder whether this repo also supports it.

**Comment by vahidk** [comment]
Not currently.
