### ISSUE TITLE
The write example does not work

### ISSUE THREAD

**Issue by OswinGuai** [vahidk/tfrecord#6]
What is wrong with my example?
```
import tfrecord
import torch
import numpy as np

image_bytes = torch.ones([10,2,2,3]).numpy().tobytes()
label = torch.ones([10]).float().numpy()
index = list(range(10))

writer = tfrecord.TFRecordWriter("example.tfrecord")
writer.write({
    "image": (image_bytes, "byte"),
    "label": (label, "float"),
    "index": (index, "int")
})
writer.close()
```

 It failed with :
<img width="472" alt="截屏2019-12-17上午12 40 16" src="https://user-images.githubusercontent.com/7878475/70925207-ce1cc880-2065-11ea-9d42-fa1e614bffc0.png">

**Comment by vahidk** [comment]
Just do pip3 install crc32c

**Comment by OswinGuai** [comment]
> Just do pip3 install crc32c

Thank you. And it is better to appear at the installation.
