### ISSUE TITLE
Question about reading binary data

### ISSUE THREAD

**Issue by leng-yue** [vahidk/tfrecord#65]
Some tf records are not tf.example, they yield a binary instead.

The following works well in `tf.data.TFRecordDataset`.
```
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
data = next(dataset.as_numpy_iterator())
sc = Scenario()
sc.ParseFromString(data)
print(sc.timestamps_seconds)
```

When I try to use tfrecord (this repo) to replace it, I found that `data` here is a dictionary.
```
dataset = TFRecordDataset(tfrecord_path, None, compression_type=None)
data = next(iter(dataset))
print(data)  # {}
```

The following is a sample from waymo motion prediction dataset
[Google Drive](https://drive.google.com/file/d/1yQAIqm_njMu1RTUHGj1C8nRfb3Aos7mg/view?usp=sharing)
[Official Protobuf](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/protos/scenario.proto)

**Comment by leng-yue** [comment]
After viewing the code, I found that I can use an internal function `tfrecord.tfrecord_iterator` to ready binary data.

**Comment by vahidk** [comment]
Yes. You can use tfrecord_iterator to implement your own reader. tfrecord_loader assumes that your file is that the records are either tf.Example or tf.SequenceExample.
