### ISSUE TITLE
this byte image data is ```open('xxx.jpg','rb').read() ```  data?

### ISSUE THREAD

**Issue by jaffe-fly** [vahidk/tfrecord#66]
https://github.com/vahidk/tfrecord/blob/74b2d24a838081356d993ec0e147eaf59ccd4c84/tfrecord/reader.py#L116

when i use ```open('xxx.jpg','rb').read() ```  to read the image, I get wrong shape
 ```
data = next(iter(loader))
print(data['image'].shape)
```
```
torch.Size([1, 12751])
```

how to do ?

**Comment by vahidk** [comment]
See readme.
