### ISSUE TITLE
__getitem__(index)

### ISSUE THREAD

**Issue by fwarmuth** [vahidk/tfrecord#67]
Hey,
how about implementing `__getitem__()` on the tfrecord dataset?
I use that function quite to exactly determine which sample i wan to look at.
regards
btw. great work!

**Comment by vahidk** [comment]
This is a duplicate issue.

**Comment by fwarmuth** [comment]
can you link the corresponding issue? is did not find in prior to opening this issue.

**Comment by vahidk** [comment]
https://github.com/vahidk/tfrecord/issues/35
