### ISSUE TITLE
Loading a multi-tfrecord multi-split dataset

### ISSUE THREAD

**Issue by sam1902** [vahidk/tfrecord#68]
I have downloaded [the `open_image_v4` dataset](https://www.tensorflow.org/datasets/catalog/open_images_v4) from Tensorflow using the `tfds` utility (as well as many other similar datasets), and now I have a folder with the following structure:
```
open_image_v4
├── open_images_v4-test.tfrecord-00001-of-00512
├── open_images_v4-test.tfrecord-00002-of-00512
├── ...
├── open_images_v4-train.tfrecord-00001-of-01024
├── ...
└── open_images_v4-validation.tfrecord-00001-of-00128
├── ...
```
As you can see, I have 3 splits: `train`, `test` and `validation`, however, each of those splits are themselves splitted/sharded into subfiles.

I created an index file for each of those TFrecord using GNU parallel:
```sh
parallel -j19 python3 -m tfrecord.tools.tfrecord2idx {} index/{}.index ::: *.tfrecord-*
```

From skimming over the reader code, it seems that you only support datasets that all fit in a single `.tfrecord` file.
Did I miss something or is there a workaround I could employ to read large subsets (train, valid, test) of the dataset?

I initially thought it might be possible to provide the input pattern as:
```py
tfrecord_pattern = "/tmp/{split}_{idx}.tfrecord"
```
or in the case of my above file system:
```py
tfrecord_pattern = "/tmp/open_images_v4-{split}.tfrecord-{idx:05d}-of-{total:05d}"
```
if that may be of any help for future PRs.

**Comment by vahidk** [comment]
You can provide a pattern to MultiTFRecordDataset and it would read and blend all of the files simultaneously. This is already supported.
