### ISSUE TITLE
Losing shape information

### ISSUE THREAD

**Issue by roymiles** [vahidk/tfrecord#69]
Hi,

I am trying to load the ImageNet2012 tfrecords (loaded using tensorflow datasets).

I can load the tfrecords using Tensorflow fine, however, when I use this library I lose the shape information of the images (they come back as flattened lists). Is there any way to resolve this? Other than that the library works great!

Thanks

**Comment by vahidk** [comment]
This is expected behavior.  You can pass a transform function to do your preprocessing.
