### ISSUE TITLE
shard not used in MultiTFRecordDataset

### ISSUE THREAD

**Issue by otaj** [vahidk/tfrecord#70]
Hi, I just noticed, that MultiTFRecordDataset does not use shard, whereas TFRecordDataset does. Is this a correct behavior? It very well could be, there could be some dark magic which I am not aware of, however, to me it seems it is not. If it is not, I can submit a PR to fix it.

Thanks :)

**Comment by vahidk** [comment]
Yes. It's currently not used. Sharding helps with parallelizing reads and better shuffling, but MultiTFRecordDataset can already read from pre-sharded data so it's not as necessary. If it doesn't overcomplicate the design we can do that.

**Comment by otaj** [comment]
I suspect that there is some issue with not using shard, since when I am using MutliTFRecordDataset with only one file, I would expect the behavior to be the same as in TFRecordDataset with the same data, which it currently isn't.

I don't really have a nice MWE, since my tfrecord files are "big" (45k SequenceExamples) and it takes quite a while to loop over it (my transform and collate_fn are *heavy*), however I suspect that it is not behaving the same with multiple workers.

I guess it in reality boils down to the need of unit tests, as you mentioned in [here](https://github.com/vahidk/tfrecord/pull/62#issuecomment-863357202). I am not sure I have a capacity for writing them at the moment
