### ISSUE TITLE
is there any way to process the TFRecordDataset?

### ISSUE THREAD

**Issue by shijian97** [vahidk/tfrecord#74]
hi, thanks for your contrubutions! I have some problems when I'm make the torch.utils.data.DataLoader(TFRecordDataset, batch_size), because the data of my tfrecrds files was encoded, so they have different length.
Is there any way to process the TFRecordDataset? or I can only preprocess in the feature descriptor?
thank you so much

**Comment by vahidk** [comment]
See readme for an example.

**Comment by shijian97** [comment]
oh I see, than you
