### ISSUE TITLE
`flat_map`

### ISSUE THREAD

**Issue by emilemathieu** [vahidk/tfrecord#76]
Hi,
Thanks for the great module!

I was wondering whether there is a way to efficiently flatten a dataset as in tf with
`ds = ds.flat_map(tf.data.Dataset.from_tensor_slices)`

Best,
Emile

**Comment by vahidk** [comment]
TFRecordDataset/MultiTFRecordDataset are implementations of Pytorch's IterableDataset. So anything yo can do with an IterableDataset you can do with TFRecordDataset too. you should be able to just built-in python map function to do that.
