### ISSUE TITLE
Is this kaggle right?

### ISSUE THREAD

**Issue by shizhaojingszj** [vahidk/tfrecord#79]
https://www.kaggle.com/hidehisaarai1213/g2net-read-from-tfrecord-train-with-pytorch

The author claimed this repo's implementation is slower? Is that true?

If it is, can sb. fix that? Is that worth it?

**Comment by vahidk** [comment]
This is a very strange request. I can't go investigate everything that some random person says on internet. You can benchmark the library yourself and see if it's a bottleneck for your training jobs. If you find a problem you can report it here.
