### ISSUE TITLE
How to specify multiple tfrecord files in the example of MultiTFRecordDataset?

### ISSUE THREAD

**Issue by OswinGuai** [vahidk/tfrecord#8]
How to specify multiple tfrecord files in the example of MultiTFRecordDataset?

**Comment by vahidk** [comment]
The pattern is fed to string format. The full path used is pattern.format(split). So if your files are "/path/to/dataset1.tfrecord" and "/path/to/dataset2.tfrecord" you provide:
tfrecord_pattern = "/path/to/{}.tfrecord"
splits = {
    "dataset1": 0.8,
    "dataset2": 0.2,
}
0.8, and 0.2 are ratios.
