### ISSUE TITLE
Error : Failed to read the record 

### ISSUE THREAD

**Issue by shwetasahu1996** [vahidk/tfrecord#91]
![image](https://github.com/vahidk/tfrecord/assets/33805418/4302a5de-3dee-41a7-8a6c-7abbb5861d2a)

Able to load others tfrecords but for few getting this error .

**Comment by vahidk** [comment]
It's impossible to help with the given information. Try stepping through the code and see where the issue is. If you find a bug you can always submit a PR. This is an open source project.
